<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Soteria-1aad100e-5cc1-467f-97c0-9d3051b4744f</UserSecretsId>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.0.0</Version>
        <InformationalVersion>1.0.0</InformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" PrivateAssets="all" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9" />
        <PackageReference Include="MudBlazor" Version="9.6.0" />
        <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.0.0" />
        <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0" />
        <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.6.0" />
        <PackageReference Include="DotNetEnv" Version="3.2.0" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

</Project>